In [5]:
import os

os.listdir("../Data_understanding")

['Project_106_Unclean_Energy_Dataset_5000.xlsx']

In [6]:
import pandas as pd

df = pd.read_excel(
    "../Data_understanding/Project_106_Unclean_Energy_Dataset_5000.xlsx",
    sheet_name="Unclean_Data"
)

df.head()

,Record_ID,Date_Time,State,Sector,Consumption_MWh,Peak_Demand_MW,Generation_MWh,Electricity_Price_USD_per_MWh,Renewable_Share_Pct,Weather_Index,Peak_Flag
0,103461,2024-05-24 04:00:00,California,INDUSTRIAL,981.86,1139.91,1128.04,51.60,23.41,40.42,No
1,103959,2024-06-13 22:00:00,Texas,Industrial,1040.52,972.13,1047.89,52.96,27.82,67.81,No
2,100066,2024-01-03 17:00:00,Florida,Residential,920.08,895.03,969.66,58.09,35.91,45.49,No
3,102520,2024-04-14 23:00:00,Texas,Residential,686.13,758.59,699.00,50.12,37.10,33.45,No
4,100394,2024-01-17 09:00:00,california,NaN,1507.38,1745.83,1596.02,65.08,19.39,59.06,Yes

In [7]:
df_clean = df.copy()

In [8]:
df_clean.isna().sum()

Record_ID                          0
Date_Time                          0
State                            126
Sector                           102
Consumption_MWh                   90
Peak_Demand_MW                    75
Generation_MWh                   102
Electricity_Price_USD_per_MWh    110
Renewable_Share_Pct               91
Weather_Index                    126
Peak_Flag                          0
dtype: int64

In [9]:
df_clean.duplicated().sum()

np.int64(25)

In [10]:
df_clean = df_clean.drop_duplicates()

In [11]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
df_clean["State"] = df_clean["State"].str.title()

In [13]:
df_clean["Sector"] = df_clean["Sector"].str.title()

Date_Time clean

In [14]:
df_clean["Date_Time"] = pd.to_datetime(df_clean["Date_Time"], errors="coerce")

In [15]:
df_clean["Date_Time"].isna().sum()

np.int64(8)

In [16]:
df_clean = df_clean.dropna(subset=["Date_Time"])

Missing values-a handle

In [17]:
df_clean["State"].isna().sum()

np.int64(125)

In [18]:
df_clean["State"] = df_clean["State"].fillna(df_clean["State"].mode()[0])

In [19]:
df_clean["Sector"] = df_clean["Sector"].fillna(df_clean["Sector"].mode()[0])

In [20]:
df_clean["Consumption_MWh"] = df_clean["Consumption_MWh"].fillna(
    df_clean["Consumption_MWh"].median()
)

In [21]:
df_clean["Peak_Demand_MW"] = df_clean["Peak_Demand_MW"].fillna(
    df_clean["Peak_Demand_MW"].median()
)

In [22]:
df_clean["Generation_MWh"] = df_clean["Generation_MWh"].fillna(
    df_clean["Generation_MWh"].median()
)

In [23]:
df_clean["Electricity_Price_USD_per_MWh"] = df_clean["Electricity_Price_USD_per_MWh"].fillna(
    df_clean["Electricity_Price_USD_per_MWh"].median()
)

In [24]:
df_clean["Renewable_Share_Pct"] = df_clean["Renewable_Share_Pct"].fillna(
    df_clean["Renewable_Share_Pct"].median()
)

In [25]:
df_clean["Weather_Index"] = df_clean["Weather_Index"].fillna(
    df_clean["Weather_Index"].median()
)

In [26]:
df_clean["Peak_Flag"].isna().sum()

np.int64(0)

invalid values

In [27]:
df_clean = df_clean[df_clean["Consumption_MWh"] >= 0]

In [28]:
df_clean = df_clean[df_clean["Generation_MWh"] >= 0]

In [29]:
df_clean = df_clean[
    (df_clean["Renewable_Share_Pct"] >= 0) &
    (df_clean["Renewable_Share_Pct"] <= 100)
]

In [30]:
(df_clean["Peak_Demand_MW"] < 0).sum()

np.int64(0)

In [31]:
df_clean.shape

(4991, 11)

missing-value verification

In [32]:
df_clean.isna().sum()

Record_ID                        0
Date_Time                        0
State                            0
Sector                           0
Consumption_MWh                  0
Peak_Demand_MW                   0
Generation_MWh                   0
Electricity_Price_USD_per_MWh    0
Renewable_Share_Pct              0
Weather_Index                    0
Peak_Flag                        0
dtype: int64

In [33]:
df_clean.describe()

,Record_ID,Date_Time,Consumption_MWh,Peak_Demand_MW,Generation_MWh,Electricity_Price_USD_per_MWh,Renewable_Share_Pct,Weather_Index
count,4.991000e+03,4991,4991.000000,4991.000000,4991.000000,4991.000000,4991.000000,4991.000000
mean,1.061075e+05,2024-04-14 04:43:44.083350,980.060775,1021.606016,1054.037691,55.147941,30.955841,49.617552
min,1.000010e+05,2024-01-01 00:00:00,341.780000,317.010000,348.520000,-63.160000,2.000000,-16.980000
25%,1.012565e+05,2024-02-22 05:30:00,778.810000,805.325000,838.415000,49.565000,23.420000,39.395000
50%,1.025080e+05,2024-04-14 04:00:00,955.950000,990.290000,1024.520000,55.090000,31.020000,49.550000
75%,1.037635e+05,2024-06-05 06:30:00,1156.225000,1202.450000,1244.810000,60.445000,38.480000,59.775000
max,1.004887e+06,2024-07-27 07:00:00,8481.665471,9193.240659,9791.911919,471.883558,71.610000,105.920000
std,5.690509e+04,NaN,326.105081,343.204473,345.857579,12.950054,10.995724,15.094740

In [34]:
df_clean.dtypes

Record_ID                                 int64
Date_Time                        datetime64[us]
State                                       str
Sector                                      str
Consumption_MWh                         float64
Peak_Demand_MW                          float64
Generation_MWh                          float64
Electricity_Price_USD_per_MWh           float64
Renewable_Share_Pct                     float64
Weather_Index                           float64
Peak_Flag                                   str
dtype: object

In [35]:
df_clean = df_clean.reset_index(drop=True)

In [36]:
df_clean.isna().sum()

Record_ID                        0
Date_Time                        0
State                            0
Sector                           0
Consumption_MWh                  0
Peak_Demand_MW                   0
Generation_MWh                   0
Electricity_Price_USD_per_MWh    0
Renewable_Share_Pct              0
Weather_Index                    0
Peak_Flag                        0
dtype: int64

In [37]:
(df_clean["Consumption_MWh"] < 0).sum()

np.int64(0)

In [38]:
(df_clean["Generation_MWh"] < 0).sum()

np.int64(0)

In [39]:
(
    (df_clean["Renewable_Share_Pct"] < 0) |
    (df_clean["Renewable_Share_Pct"] > 100)
).sum()

np.int64(0)

In [40]:
(df_clean["Peak_Demand_MW"] < 0).sum()

np.int64(0)

In [41]:
(df_clean["Electricity_Price_USD_per_MWh"] < 0).sum()

np.int64(8)

In [42]:
df_clean.shape

(4991, 11)

In [43]:
df_clean.to_excel(
    "../Data_Audit_Cleaning/Cleaned_Dataset.xlsx",
    index=False
)